version: '3.8'

services:
  # Single-image application (UI + API + Nginx)
  app:
    build:
      context: .
      dockerfile: Dockerfile.single
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=Practice Software Testing
      - APP_ENV=local
      - APP_DEBUG=false
      - APP_KEY=base64:YOUR_KEY_WILL_BE_GENERATED
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=toolshop
      - DB_USERNAME=toolshop_user
      - DB_PASSWORD=secret_password
      - SEED_DATABASE=true
      - LOG_CHANNEL=stderr
      - SESSION_DRIVER=file
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=toolshop
      - MYSQL_USER=toolshop_user
      - MYSQL_PASSWORD=secret_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
